[package]
name = "methods"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = { version = "1.1.2" }

[package.metadata.risc0]
methods = [
    "sha",
    "fib",
    "merkle",
    "poseidon",
]

[profile.release]
lto = true
opt-level = 3